config/routes.rb
Nycuniteddragons::Application.routes.draw do

  root :to => 'home#index'

  get '/about' => 'home#about'
  get '/join' => 'home#join'
  get '/training' => 'home#training'
  get '/schedule' => 'home#schedule'
  get '/media' => 'home#media'
  get '/contact' => 'home#contact'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def join
  end

  def training
  end

  def schedule
  end

  def media
  end

  def contact
  end

  def is_practice_on
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/about.html.erb
<div class="row featurette" id="who-we-are">
  <div class="col-md-7">
    <h2 class="featurette-heading">Who We Are</h2>
    <p class="lead">The NYC United Dragons is comprised of elite paddlers from varying dragon boat clubs and paddling associations.
      These individuals have joined together to compete in the sport of dragon boat racing. United Dragons are not club-exclusive and
      encourage paddlers to continue paddling on their home teams and clubs. All that is asked is that paddlers commit to a handful of
      high-profile and international regattas.</p>
  </div>
  <div class="col-md-5">
    <img class="featurette-image img-responsive" src="<%= asset_path('rhode_island_engine_back.jpg')%>" >
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette" id="our-mission-statement">
  <div class="col-md-5">
    <img class="featurette-image img-responsive" src="<%= asset_path('rhode_island_wus_coaches.jpg')%>" >
  </div>
  <div class="col-md-7">
    <h2 class="featurette-heading">Our Mission Statement</h2>
    <p class="lead">
      We the NYC United Dragons believe in the following objectives:
      <ul>
        <li>Pursuit of excellence:
          <ul>
            <li>Obtain podium finish in all events</li>
            <li>Continuous development through offered training opportunities</li>
            <li>Grow our team through recruitment of talented and committed athletes</li>
          </ul>
        </li>
        <li>All members of the club are treated with equal respect and integrity</li>
        <li>Communication: Expectations are clear and communicated across all team members concerning participation, training, selection, and costs of the season.</li>
        <li>Assist in the development of all participants regardless of level (introductory, novice, advanced, recreational and/or competitive)</li>
        <li>Long term athlete development and team commitment</li>
      </ul>
    </p>
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette" id="achievements">
  <div class="col-md-7">
    <h2 class="featurette-heading">Achievements</h2>
    <p class="lead">
    <ul>
      <li>2013 Season - our first ever!
        <ul>
          <li>Bronze - Mixed Division A - <a href="http://riverfront.org/events/riverfront-dragon-boat-asian-festival" target="_blank">Riverfront Dragon Boat & Asian Festival in Hartford, CT</a></li>
          <li>Grand Champion - Dragon Division - <a href="http://www.dragonboatri.com/" target="_blank">Rhode Island Chinese Dragon Boat Races</a></li>
          <li>Silver - Sport Mixed Grand A Division - <a href="http://www.gwndragonboat.com/Default.asp?id=18&l=1" target="_blank">GWN Mercer County Dragon Boat Festival in Princeton, NJ</a></li>
        </ul>
      </li>
    </ul>
    </p>
  </div>
  <div class="col-md-5">
    <img class="featurette-image img-responsive" src="<%= asset_path('rhode_island_stage.jpg')%>" >
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette" id="what-is-dragonboat">
  <div class="col-md-5">
    <img class="featurette-image img-responsive" src="<%= asset_path('ithaca.jpg')%>" >
  </div>
  <div class="col-md-7">
    <h2 class="featurette-heading">What is Dragon Boat?</h2>
    <p class="lead">A dragon boat is a human powered boat (Paddled Water Craft) traditionally made of teak wood (in modern day the sport has seen the surge of boats made with fiberglass propelled by high tech carbon fiber paddles) in various designs and sizes. It is one of a family of Traditional Long Boats found throughout Asia, Africa and the Pacific Islands. The boat is used in dragon boat racing which originated in China over 2000 years ago.</p>
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette" id="dragonboating-worldwide">
  <div class="col-md-7">
    <h2 class="featurette-heading">Dragon boating worldwide.</h2>
    <p class="lead">Today, dragon boat is one of the world's fastest growing water sports. It is currently the second most popular team sport in the world; only soccer surpasses it. There are nearly 50 million people who currently take part annually in dragon boat races worldwide. Dragon boat races are held in countries all around the world. The majority of the racers are in China and the Far East. It is estimated that over 150,000 participants are in Europe, 50,000 in North America, and 20,000 in Australia.</p>
  </div>
  <div class="col-md-5">
    <img class="featurette-image img-responsive" src="<%= asset_path('idbf_2013.jpg')%>" >
  </div>
</div>

app/views/home/contact.html.erb
<div class="row featurette" id="practices">
  <div class="col-md-7">
    <h2 class="featurette-heading">Contact Us</h2>
    <p class="lead">
      If you would like to learn more about us and our club, send us an email to
      <a href="mailto:nycuniteddragons@gmail.com" target="_blank">nycuniteddragons@gmail.com</a> We look forward to hearing from you!
    </p>
  </div>
  <div class="col-md-5">
    <img class="featurette-image img-responsive" src="<%= asset_path('meeting_on_the_water.jpg')%>" >
  </div>
</div>


<!-- Marketing messaging and featurettes
 ================================================== -->
 <!-- Wrap the rest of the page in another container to center all the content. -->

 <div class="container marketing">

   <% if false %>
   <!-- Three columns of text below the carousel -->
   <div class="row">
     <div class="col-lg-4">

       <h2>Heading</h2>
       <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
       <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
     </div><!-- /.col-lg-4 -->
     <div class="col-lg-4">
       <img class="img-circle" src="data:image/png;base64," data-src="holder.js/140x140" alt="Generic placeholder image">
       <h2>Heading</h2>
       <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
       <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
     </div><!-- /.col-lg-4 -->
     <div class="col-lg-4">
       <img class="img-circle" src="data:image/png;base64," data-src="holder.js/140x140" alt="Generic placeholder image">
       <h2>Heading</h2>
       <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
       <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
     </div><!-- /.col-lg-4 -->
   </div><!-- /.row -->

       <% end %>
 </div><!-- /.container -->

app/views/home/index.html.erb
<!-- Carousel
 ================================================== -->
 <div id="myCarousel" class="carousel slide">
   <!-- Indicators -->
   <ol class="carousel-indicators">
     <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
     <li data-target="#myCarousel" data-slide-to="1"></li>
     <li data-target="#myCarousel" data-slide-to="2"></li>
   </ol>
   <div class="carousel-inner">
     <div class="item active">
       <%= image_tag "rhode_island_engine.jpg" %>
       <div class="container">
         <div class="carousel-caption">
           <h1>NYC United Dragons</h1>
           <p>The alliance of elite paddlers across various clubs to form a premier Dragonboat crew, proudly representing NYC.</p>
           <p><%= link_to "Read Who We Are", about_path + "#who-we-are", :class => "btn btn-large btn-primary" %></p>
         </div>
       </div>
     </div>
     <div class="item">
       <%= image_tag "kevin_and_tony_race.jpg" %>
       <div class="container">
         <div class="carousel-caption">
           <h1>Be the best paddler you can be</h1>
           <p>No membership fees. Plus get free outrigger canoe training and dragon boat practices</p>
         </div>
       </div>
     </div>
     <div class="item">
       <%= image_tag "mercer_awards.jpg" %>
       <div class="container">
         <div class="carousel-caption">
           <h1>Ready to join in?</h1>
           <p>Tryouts run all year long</p>
           <p><%= link_to "Check out our Testing", join_path+"#testing", :class => "btn btn-large btn-primary" %></p>
         </div>
       </div>
     </div>
   </div>
   <a class="left carousel-control" href="#myCarousel" data-slide="prev">
     <span class="glyphicon glyphicon-chevron-left"></span>
   </a>
   <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right white"></span></a>
 </div><!-- /.carousel -->

 <!-- Marketing messaging and featurettes
 ================================================== -->
 <!-- Wrap the rest of the page in another container to center all the content. -->

 <div class="container marketing">



   <!-- Three columns of text below the carousel -->
   <div class="row">
     <% if false %>
     <div class="col-lg-4">
       <a href="https://www.facebook.com/groups/WorldsFairOC1/?fref=ts" targe="_blank"><i class="icon icon-facebook-sign"></i></a>
       <h2>Us on Facebook</h2>
       <p>Check this out for updates on available OC paddling time slots. Also watch some sweet GoPro videos
         of our runs.</p>
     </div><!-- /.col-lg-4 -->

     <div class="col-lg-4">
       <img class="img-circle" src="data:image/png;base64," data-src="holder.js/140x140" alt="Generic placeholder image">
       <h2>Heading</h2>
       <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
       <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
     </div><!-- /.col-lg-4 -->
     <div class="col-lg-4">
       <img class="img-circle" src="data:image/png;base64," data-src="holder.js/140x140" alt="Generic placeholder image">
       <h2>Heading</h2>
       <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
       <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
     </div><!-- /.col-lg-4 -->
     <% end %>
   </div><!-- /.row -->

 </div><!-- /.container -->

app/views/home/join.html.erb
<div class="row featurette" id="who-we-are">
  <div class="col-md-7">
    <h2 class="featurette-heading">Join Us!</h2>
    <p class="lead">
      Our crew is open to all paddlers from any club. Our home is the World's Fair Marina in Queens, NYC behind Citi Field.
      Our crew is made up of over 30 individuals, all of whom live in the NYC Metropolitan area.
      All of our members are 18+ yrs old but youth members are always welcome (we just ask that you and your parental guardian <%= link_to "sign the club waiver", asset_path('WFMCC_Electronic_Waiver.pdf') %>).
    </p>
  </div>
  <div class="col-md-5">
    <iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=d&amp;source=s_q&amp;hl=en&amp;geocode=%3BCQ_blQYYE3KtFYXybQIdsCaZ-yl17Py85l_CiTGlS-Zf740hgg&amp;q=World's+Fair+Marina,+Willets+Point,+NY&amp;aq=0&amp;oq=world's+fair+&amp;sll=40.748395,-73.847308&amp;sspn=0.025814,0.048108&amp;ie=UTF8&amp;hq=&amp;hnear=World's+Fair+Marina,+Flushing,+Queens,+New+York+11368&amp;t=m&amp;daddr=World's+Fair+Marina,+Flushing,+NY+11368&amp;ll=40.759941,-73.849168&amp;spn=0.006295,0.008311&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?f=d&amp;source=embed&amp;hl=en&amp;geocode=%3BCQ_blQYYE3KtFYXybQIdsCaZ-yl17Py85l_CiTGlS-Zf740hgg&amp;q=World's+Fair+Marina,+Willets+Point,+NY&amp;aq=0&amp;oq=world's+fair+&amp;sll=40.748395,-73.847308&amp;sspn=0.025814,0.048108&amp;ie=UTF8&amp;hq=&amp;hnear=World's+Fair+Marina,+Flushing,+Queens,+New+York+11368&amp;t=m&amp;daddr=World's+Fair+Marina,+Flushing,+NY+11368&amp;ll=40.759941,-73.849168&amp;spn=0.006295,0.008311" style="color:#0000FF;text-align:left">View Larger Map</a></small>
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette" id="testing">
  <div class="col-md-5">
    <img class="featurette-image img-responsive" src="<%= asset_path('indoor_erg.jpg')%>" >
  </div>
  <div class="col-md-7">
    <h2 class="featurette-heading">Testing</h2>
    <p class="lead">
      Member selection is based on testing, either on outrigger canoes or ERG machines. But as a result, there is <strong>no membership fee.</strong>
      Paddlers are only responsible for their own racing fees and expenses. There are several timed testing methods to determine seating:
      <ul>
        <li>200M OC-1 Sprint</li>
        <li>200M OC-2 Sprint, back person is steering only</li>
        <li>200M One-man Dragonboat paddle</li>
        <li>300M ERG Concept 2 Row with Dragonboat attachment</li>
      </ul>
    </p>
  </div>
</div>

app/views/home/media.html.erb
<!-- Marketing messaging and featurettes
 ================================================== -->
 <!-- Wrap the rest of the page in another container to center all the content. -->

 <div class="container marketing">

   Coming soon!
   <% if false %>
   <!-- Three columns of text below the carousel -->
   <div class="row">
     <div class="col-lg-4">

       <h2>Heading</h2>
       <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
       <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
     </div><!-- /.col-lg-4 -->
     <div class="col-lg-4">
       <img class="img-circle" src="data:image/png;base64," data-src="holder.js/140x140" alt="Generic placeholder image">
       <h2>Heading</h2>
       <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
       <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
     </div><!-- /.col-lg-4 -->
     <div class="col-lg-4">
       <img class="img-circle" src="data:image/png;base64," data-src="holder.js/140x140" alt="Generic placeholder image">
       <h2>Heading</h2>
       <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
       <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
     </div><!-- /.col-lg-4 -->
   </div><!-- /.row -->

       <% end %>

 </div><!-- /.container -->

app/views/home/schedule.html.erb
<div class="row featurette" id="practices">
  <div class="col-md-7">
    <h2 class="featurette-heading">Practices</h2>
    <p class="lead">
      All members are encouraged to practice with their home teams.<br />
      Prior to race day, there will be mandatory team practices (at the <a href="http://goo.gl/maps/A0ub8" target="_blank">World's Fair Marina</a>) to review the race plan.
    </p>

  </div>
  <div class="col-md-5">
    <img class="featurette-image img-responsive" src="<%= asset_path('kevin_and_tony_race.jpg')%>" >
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette" id="races">
  <div class="col-md-5">
    <img class="featurette-image img-responsive" src="<%= asset_path('rhode_island_boat_side.jpg')%>" >
  </div>
  <div class="col-md-7">
    <h2 class="featurette-heading">Races</h2>
    <p class="lead">
      We unite for only a couple high-profile regattas out of the year. Every seat on the boat is earned.
      <ul>
        <li><a href="http://dragonboats.com/" target="_blank">Toronto International Dragon Boat Festival</a> - June 22-23, 2013s</li>
        <li><a href="http://riverfront.org/events/riverfront-dragon-boat-asian-festival" target="_blank">Riverfront Dragon Boat Festival</a> - August 16-17, 2013</li>
        <li><a href="http://www.dragonboatri.com/" target="_blank">Rhode Island Chinese Dragon Boat Races</a> - September 7, 2013</li>
        <li><a href="http://www.gwndragonboat.com/Default.asp?id=18&l=1" target="_blank">Mercer County Dragon Boat Festival</a> - September 14-15, 2013</li>
      </ul>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>NYC United Dragon Boat Crew</title>

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">

  <%= csrf_meta_tags %>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="../../assets/js/html5shiv.js"></script>
    <script src="../../assets/js/respond.min.js"></script>
  <![endif]-->

</head>
<body>

<div class="navbar-wrapper">
  <div class="container">

    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "NYC United Dragon Boat Crew", root_path, :class => 'navbar-brand' %>

        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
            <li class="dropdown">
              <a id="drop-about" role="button" class="dropdown-toggle" data-toggle="dropdown" href="/about">About <b class="caret"></b></a>
              <ul id="about-menu" class="dropdown-menu" role="menu" aria-labelledby="drop-about">
                <li role="presentation"><%= link_to "Who We Are", about_path + "#who-we-are" %></li>
                    <li role="presentation"><%= link_to "Our Mission Statement", about_path + "#our-mission-statement" %></li>
                    <li role="presentation"><%= link_to "Achievements", about_path + "#achievements" %></li>
                    <li role="presentation"><%= link_to "What is Dragon Boat", about_path + "#what-is-dragonboat" %></li>
                    <li role="presentation"><%= link_to "Dragonboating Worldwide", about_path + "#dragonboating-worldwide" %></li>
              </ul>
            </li>
            <li class="dropdown <%= 'active' if current_page?(join_path) %>">
              <a id="drop-join" role="button" class="dropdown-toggle" data-toggle="dropdown" href="<%= join_path %>">Join <b class="caret"></b></a>
              <ul id="join-menu" role="menu" class="dropdown-menu" aria-labelledby="drop-join">
                <li role="presentation"><%= link_to "Join Us", join_path %></li>
                <li role="presentation"><%= link_to "Testing", join_path+"#testing" %></li>
                <li role="presentation"><%= link_to "Waiver", asset_path('WFMCC_Electronic_Waiver.pdf') %></li>
              </ul>
            </li>
            <li class="dropdown <%= 'active' if current_page?(schedule_path) %>">
              <a id="drop-schedule" role="button" data-toggle="dropdown" href="<%= schedule_path %>">Schedule <b class="caret"></b></a>
              <ul id="schedule-menu" class="dropdown-menu" role="menu" aria-labelledby="drop-schedule">
                <li role="presentation"><%= link_to "Practices", schedule_path+"#practices", :role => 'menuitem' %></li>
                <li role="presentation"><%= link_to "Races", schedule_path+"#races", :role => 'menuitem' %></li>
              </ul>
            </li>
            <li class="<%= 'active' if current_page?(media_path) %>"><%= link_to "Media", media_path %></li>
            <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Contact", contact_path %></li>
            <li class="dropdown">
              <a id="drop-links" role="button" class="dropdown-toggle" data-toggle="dropdown" href="#">Links <b class="caret"></b></a>
              <ul id="links-menu" role="menu" class="dropdown-menu" aria-labelledby="drop-links">
                <li role="presentation"><a href="http://puffpuffdragons.com" target="_blank">Puff Puff Dragons</a></li>
                <li role="presentation"><a href="http://nycwfmcc.com" target="_blank">Worlds Fair Marina Canoe Club</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>

  </div>
</div>

<%= yield %>


<!-- FOOTER -->
   <footer>
     <p class="pull-right"><a href="#">Back to top</a></p>
     <p><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">NYC United Dragons</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://amanda.li" property="cc:attributionName" rel="cc:attributionURL">Amanda Li</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US">Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License</a>.</p>
   </footer>

<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

</body>
</html>